// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eWorldCup2.Infrastructure;

#nullable disable

namespace eWorldCup2.Infrastructure.Migrations
{
    [DbContext(typeof(WorldCupDbContext))]
    [Migration("20251126120851_AddTournamentAndMatchTables")]
    partial class AddTournamentAndMatchTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eWorldCup2.Domain.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("Player1Id")
                        .HasColumnType("int");

                    b.Property<int>("Player1Wins")
                        .HasColumnType("int");

                    b.Property<int>("Player2Id")
                        .HasColumnType("int");

                    b.Property<int>("Player2Wins")
                        .HasColumnType("int");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("eWorldCup2.Domain.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Charlie"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Diana"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ethan"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Fiona"
                        },
                        new
                        {
                            Id = 7,
                            Name = "George"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Hannah"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Isaac"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Julia"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Kevin"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Laura"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Michael"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Nina"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Oscar"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Paula"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Quentin"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Rachel"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Samuel"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Tina"
                        });
                });

            modelBuilder.Entity("eWorldCup2.Domain.Models.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentRound")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfPlayers")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });
#pragma warning restore 612, 618
        }
    }
}
